In [3]:
import numpy as np
a=np.array([0,1,2,3])

In [2]:
print(a)

[0 1 2 3]


In [3]:
print(np.arange(8))

[0 1 2 3 4 5 6 7]


In [4]:
a.ndim

1

In [5]:
a.shape

(4,)

In [6]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [7]:
b.ndim

2

In [8]:
import numpy as np
c=np.array([[[0,1],[2,3],[4,5],[6,7]]])
print(c)  
c.ndim                                                 ## 3-d

[[[0 1]
  [2 3]
  [4 5]
  [6 7]]]


3

In [9]:
c.shape

(1, 4, 2)

In [10]:
a=np.linspace(0,1,6)

In [11]:
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [12]:
a=np.ones((3,3))

In [13]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
a=np.ones((3,3),dtype=int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [17]:
a=np.diag((1,2,3,4))

In [18]:
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [19]:
a=np.diag(a)


In [20]:
print(a)

[1 2 3 4]


In [21]:
a=np.random.rand(4)

In [22]:
print(a)

[0.29720228 0.86604883 0.44193827 0.23942973]


In [23]:
a=np.random.random(4)
print(a)

[0.34441889 0.99624607 0.4614778  0.79657683]


In [24]:
a=np.arange(10)
a.dtype

dtype('int32')

In [25]:
a=np.arange(10,dtype='float64')

In [26]:
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [27]:
a=np.zeros((3,3))

In [28]:
a[2,1]=5

In [29]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 5. 0.]]


In [30]:
a=np.arange(10)
b=np.arange(5)
a[5:]=b[ : :-1]
print(a)

[0 1 2 3 4 4 3 2 1 0]


In [31]:
# fancy indexing

a=np.random.randint(0,20,15)
print(a)
mask=(a%2==0)
extracted=a[mask]
print(extracted)

[ 3 14  1  2 11  9 12 19  4  5 14 12 12  7 14]
[14  2 12  4 14 12 12 14]


In [32]:
print(a[mask]=-1)

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (Temp/ipykernel_2596/2038101388.py, line 1)

In [4]:
a=np.array([1,1,0,0], dtype=bool)
b=np.array([1,0,1,0], dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [5]:
np.sin(a)

array([0.8413, 0.8413, 0.    , 0.    ], dtype=float16)

In [6]:
a=np.arange(6)
a.shape=(3,2)
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [8]:
b=a.reshape(1,6)
print(b)

[[0 1 2 3 4 5]]


In [10]:
a=np.arange(6)
a2=a[np.newaxis,:]
print(a)
print(a.shape)
print(a2)
print(a2.shape)

[0 1 2 3 4 5]
(6,)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [7]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [9]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
arr=np.array([2,1,4,7,6,5])
np.sort(arr)

array([1, 2, 4, 5, 6, 7])

In [10]:
data=np.array([1,2])
ones=np.ones(2,dtype=int)
a=data+ones
print(a)

[2 3]


In [11]:
a=np.array([1,2,3,4])
a.sum()

10

In [13]:
b=np.array([[1,1],[2,2]])
sum=b.sum(axis=0)
print(sum)

[3 3]


In [14]:
print(data*1.6)

[1.6 3.2]


In [15]:
data.sum()

3

In [16]:
data.min()

1

In [17]:
rng.integers(5,size=(2,4))

NameError: name 'rng' is not defined

In [23]:
mat=np.array([[1,2,3],
   [4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [24]:
print(mat.T)

[[1 4]
 [2 5]
 [3 6]]
