In [1]:
! pip install torch

In [5]:
import torch
import numpy as np
from torch import nn
import matplotlib.pyplot as plt

In [3]:
x=torch.ones(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [4]:
x=torch.rand(3,2)
print(x)

tensor([[0.6001, 0.7321],
        [0.6558, 0.1483],
        [0.8823, 0.0816]])


In [5]:
x=torch.rand(10)
print(x)

tensor([0.7142, 0.8277, 0.7845, 0.9017, 0.9899, 0.6762, 0.2208, 0.0816, 0.1061,
        0.7876])


In [6]:
x=torch.empty(3,2)
print(x)

tensor([[1.3517e+22, 2.1476e-04],
        [1.3298e+22, 4.2488e-05],
        [1.3371e+22, 1.0558e-08]])


In [7]:
y=torch.zeros_like(x)
print(y)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [8]:
x=torch.linspace(0, 1, steps=5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [9]:
x=torch.tensor([[1,2],[3,4],[5,6]])  # explicitly defining tensor
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


slicing tensor

In [10]:
print(x.size())
print(x[:,1])
print(x[0,:])

torch.Size([3, 2])
tensor([2, 4, 6])
tensor([1, 2])


In [11]:
y=x[1,1]
print(y)
print(y.item()) # to get value

tensor(4)
4


reshaping tensor

In [12]:
print(x)
y=x.view(2,3)
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [13]:
y=x.view(6,-1)
print(y)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [14]:
x=torch.ones([3,2])  
y=torch.ones([3,2])
z=x+y     # element wise operation
print(z)
z=x-y
print(z)


tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [15]:
z=y.add(x) 
print(z)  # another way to add
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [16]:
z=y.add_(x)
print(z)
print(y)   # here y also gets change

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


Numpy <> Torch

In [17]:
x_np=x.numpy() # pytorch to numpy
print(type(x),type(x_np))

<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [18]:
a=np.random.randn(5) # numpy to pytorch
print(a)
a_pt=torch.from_numpy(a)
print(type(a),type(a_pt))
print(a_pt)

[-1.20510208 -0.25847643 -1.0978086  -0.66658819  0.60862213]
<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([-1.2051, -0.2585, -1.0978, -0.6666,  0.6086], dtype=torch.float64)


In [19]:
np.add(a,1,out=a)
print(a)
print(a_pt)

[-0.20510208  0.74152357 -0.0978086   0.33341181  1.60862213]
tensor([-0.2051,  0.7415, -0.0978,  0.3334,  1.6086], dtype=torch.float64)


In [20]:
%%time
for i in range(100):
    a=np.random.randn(100,100)
    b=np.random.randn(100,100)
    c=a*b

Wall time: 59.8 ms


In [21]:
%%time
for i in range(100):
    a=torch.randn(100,100)
    b=torch.randn(100,100)
    c=a*b

Wall time: 23.5 ms


In [22]:
print(torch.cuda.device_count())

0


In [23]:
x=torch.ones([3,2],requires_grad=True)# rg means later we can use x in some func for diff
print(x)


tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [24]:
y=x+5
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [25]:
z=y*y+1
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [26]:
t=torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [27]:
t.backward() # going backward

In [28]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [29]:
x=torch.ones([3,2], requires_grad=True)
y= x + 5
r = 1/ (1+ torch.exp(-y))
print(r)
s= torch.sum(r)  
print(s)
s.backward() # here no argument as s is a single value
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor(5.9852, grad_fn=<SumBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [30]:
x=torch.ones([3,2], requires_grad=True)
y= x + 5
r = 1/ (1+ torch.exp(-y))
a= torch.ones([3,2]) # same size a r
print(s)
r.backward(a) # here argument is a required as r is tensor with multiple values  
print(x.grad)

tensor(5.9852, grad_fn=<SumBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


Autograd ex that looks like we have been doing

In [31]:
x=torch.randn([20,1],requires_grad=True)
y=3*x-2

In [32]:
w=torch.tensor([1.],requires_grad=True) # initial value of w and b
b=torch.tensor([1.],requires_grad=True)
y_hat=w*x+b
loss=torch.sum((y_hat-y)**2)

In [33]:
print(loss)

tensor(292.8723, grad_fn=<SumBackward0>)


In [34]:
loss.backward()

In [35]:
print(w.grad,b.grad)

tensor([-77.8298]) tensor([143.3617])


with loop:

In [36]:
lr=0.01
w=torch.tensor([1.],requires_grad=True) # initial value of w and b
b=torch.tensor([1.],requires_grad=True)
print(w.item(),b.item())
for i in range(10):
    x=torch.randn([20,1])
    y=3*x-2
    y_hat=w*x+b
    loss=torch.sum((y_hat-y)**2)
    loss.backward()
    with torch.no_grad(): # to stop further computation 
        w-=lr*w.grad
        b-=lr*b.grad
        w.grad.zero_()  # setting w and b grad =0 every time 
        b.grad.zero_()
    print(w.item(),b.item())
    

1.0 1.0
1.4842497110366821 0.12039399147033691
2.264317512512207 -0.6087255477905273
2.661627769470215 -1.232604742050171
2.796391487121582 -1.5410910844802856
2.8523926734924316 -1.725502848625183
2.8806164264678955 -1.824867606163025
2.899369478225708 -1.8882322311401367
2.9706077575683594 -1.947482943534851
2.978013277053833 -1.9678585529327393
2.992701530456543 -1.981931209564209


In [37]:
%%time
learning_rate=0.001
N=1000
epochs=2000

w=torch.randn([N], requires_grad=True)
b=torch.ones([1], requires_grad=True)
print(torch.mean(w).item(), b.item())

for i in range(epochs):
    x = torch.randn([N])
    y = torch.dot(3 * torch.ones([N]) ,x)-2

    y_hat=torch.dot(w,x)+b
    loss = torch.sum((y_hat - y)**2)

    loss.backward()

    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

        w.grad.zero_()
        b.grad.zero_()
    print(torch.mean(w).item(),b.item())

-0.0442064143717289 1.0
-0.03930744528770447 1.1940398216247559
-0.039076004177331924 1.1671843528747559
-0.03880814090371132 1.137174129486084
-0.032782867550849915 0.8953714370727539
-0.022626817226409912 0.6733515858650208
-0.02206665836274624 0.6475749015808105
-0.02049885503947735 0.7401066422462463
-0.012740995734930038 1.013157606124878
-0.0126412995159626 1.038023591041565
-0.012789689004421234 1.056345820426941
0.0010215826332569122 0.7511469125747681
0.0023386641405522823 0.8316739797592163
0.02760409563779831 1.1837447881698608
0.042046334594488144 0.8894386291503906
0.05063236877322197 0.7044546604156494
0.058674804866313934 0.44987204670906067
0.06600215286016464 0.24985267221927643
0.0662790983915329 0.268928587436676
0.06577958166599274 0.37634938955307007
0.06808397173881531 0.24551254510879517
0.0682448148727417 0.2069547325372696
0.07097247242927551 0.04054032266139984
0.08318903297185898 0.2752739191055298
0.08662795275449753 0.13273441791534424
0.09574388712644577 -

1.0594615936279297 -2.72418475151062
1.0592091083526611 -2.7361764907836914
1.0594308376312256 -2.5607213973999023
1.067139744758606 -2.3159217834472656
1.0662301778793335 -2.0986008644104004
1.066293478012085 -2.048971652984619
1.0663059949874878 -2.0479235649108887
1.073818325996399 -2.141533136367798
1.081976294517517 -2.4408230781555176
1.0818266868591309 -2.4733307361602783
1.0902639627456665 -2.8201775550842285
1.0994035005569458 -3.2981507778167725
1.0993388891220093 -3.497486114501953
1.0995160341262817 -3.465303659439087
1.1023337841033936 -3.370405912399292
1.102027416229248 -3.2459163665771484
1.100147008895874 -3.503084897994995
1.1003139019012451 -3.466520309448242
1.104766845703125 -3.6742405891418457
1.1113814115524292 -3.8275809288024902
1.1208066940307617 -4.078543663024902
1.120303750038147 -4.313787460327148
1.1169546842575073 -4.243567943572998
1.1206388473510742 -4.526618480682373
1.1208264827728271 -4.576117038726807
1.121652364730835 -4.678152084350586
1.12237691

1.8231391906738281 -6.1982645988464355
1.8224612474441528 -6.169501781463623
1.829219937324524 -5.738592624664307
1.8268101215362549 -5.6224822998046875
1.8271362781524658 -5.57957649230957
1.8295782804489136 -5.511753082275391
1.825081467628479 -5.867676734924316
1.816619634628296 -5.587522506713867
1.8244706392288208 -5.248555660247803
1.8256877660751343 -5.3226752281188965
1.8365715742111206 -5.542597770690918
1.8370616436004639 -5.616947650909424
1.8370527029037476 -5.614010334014893
1.8437652587890625 -5.942183494567871
1.853135585784912 -5.652385711669922
1.8567006587982178 -5.89172887802124
1.8543944358825684 -5.987000942230225
1.8554530143737793 -6.091933727264404
1.8825350999832153 -6.439822196960449
1.8909289836883545 -6.657681941986084
1.8915256261825562 -6.494488716125488
1.9025113582611084 -6.9728264808654785
1.9054902791976929 -7.357344150543213
1.9052817821502686 -7.3270745277404785
1.9123109579086304 -7.112647533416748
1.9064968824386597 -6.9387335777282715
1.9196455478

2.3092784881591797 -8.482460975646973
2.3136682510375977 -8.319929122924805
2.3078079223632812 -7.932744979858398
2.3067166805267334 -8.13927173614502
2.305521249771118 -7.943577766418457
2.305347442626953 -8.012465476989746
2.3063852787017822 -8.121186256408691
2.3064281940460205 -8.202146530151367
2.306381940841675 -8.2134428024292
2.3107478618621826 -7.988644599914551
2.3124866485595703 -8.052721977233887
2.313830614089966 -7.946444511413574
2.3164405822753906 -8.118078231811523
2.320763111114502 -7.855803966522217
2.321094036102295 -7.875576496124268
2.325432538986206 -7.748368263244629
2.3256447315216064 -7.878086566925049
2.327913761138916 -7.824573040008545
2.330942153930664 -7.945402145385742
2.3448305130004883 -8.430740356445312
2.343212366104126 -8.467119216918945
2.3460915088653564 -8.377713203430176
2.3669443130493164 -8.792818069458008
2.355731725692749 -8.541015625
2.358302354812622 -8.724026679992676
2.357775926589966 -8.735397338867188
2.3586246967315674 -8.549659729003

2.5506718158721924 -7.192075729370117
2.5544750690460205 -6.8626861572265625
2.557281970977783 -6.980860710144043
2.582637310028076 -7.539003372192383
2.5829238891601562 -7.8229780197143555
2.5868749618530273 -8.148694038391113
2.5867037773132324 -8.164568901062012
2.5847580432891846 -7.936633110046387
2.599611282348633 -8.301797866821289
2.6079158782958984 -8.587438583374023
2.6074612140655518 -8.49439525604248
2.603668689727783 -8.278199195861816
2.6016218662261963 -8.328963279724121
2.610553503036499 -8.101497650146484
2.610788583755493 -8.125971794128418
2.6111245155334473 -8.189708709716797
2.6093602180480957 -8.119937896728516
2.608433246612549 -8.148028373718262
2.6115334033966064 -8.610027313232422
2.609339714050293 -8.50329875946045
2.6216824054718018 -8.14845085144043
2.6196844577789307 -7.820672988891602
2.6142656803131104 -7.634228229522705
2.6178812980651855 -7.899115085601807
2.6204288005828857 -7.821977138519287
2.6204328536987305 -7.7956414222717285
2.6189799308776855 -

2.899576425552368 -7.421171188354492
2.898231029510498 -7.3842878341674805
2.9078140258789062 -7.232994079589844
2.9170544147491455 -7.4573469161987305
2.915285110473633 -7.414877891540527
2.9154295921325684 -7.403855800628662
2.906754493713379 -7.106099605560303
2.9015958309173584 -7.01320743560791
2.902160167694092 -7.029806613922119
2.9048304557800293 -7.142120838165283
2.896577835083008 -7.4953999519348145
2.896388292312622 -7.515254497528076
2.896909475326538 -7.395898818969727
2.889932632446289 -7.506621837615967
2.8922786712646484 -7.439008712768555
2.8935070037841797 -7.6742329597473145
2.895670175552368 -7.303089141845703
2.894443988800049 -7.453369617462158
2.892298698425293 -7.391792297363281
2.894266128540039 -7.480255126953125
2.894251823425293 -7.484710216522217
2.896345853805542 -7.644923210144043
2.9051010608673096 -7.801705837249756
2.906865119934082 -7.89402961730957
2.9090309143066406 -7.771664142608643
2.9161524772644043 -7.952068328857422
2.9212749004364014 -8.2622

3.034799337387085 -9.142354965209961
3.04012393951416 -8.757257461547852
3.042217493057251 -8.954022407531738
3.0412919521331787 -8.696676254272461
3.0417728424072266 -8.810162544250488
3.0533039569854736 -8.603251457214355
3.047431707382202 -8.904309272766113
3.0471200942993164 -8.895071983337402
3.0457398891448975 -8.99020004272461
3.0460386276245117 -8.723506927490234
3.036381483078003 -8.887009620666504
3.036403179168701 -8.907319068908691
3.035024642944336 -8.849935531616211
3.0326409339904785 -8.970534324645996
3.0326521396636963 -8.982967376708984
3.0323822498321533 -8.950719833374023
3.034925937652588 -8.695232391357422
3.030437707901001 -8.79150104522705
3.0249762535095215 -8.998396873474121
3.0322377681732178 -8.807784080505371
3.0264077186584473 -8.99634075164795
3.0237181186676025 -9.049352645874023
3.020915985107422 -8.974753379821777
2.9883108139038086 -8.53361988067627
2.989071846008301 -8.595932006835938
2.987239360809326 -8.693076133728027
2.9854750633239746 -8.6077117

3.0085082054138184 -4.466375350952148
3.002365827560425 -4.311026096343994
3.002150774002075 -4.572816848754883
3.007828712463379 -5.003777980804443
3.0063276290893555 -4.958388805389404
3.0273663997650146 -4.543323993682861
3.024421215057373 -4.810593128204346
3.026993989944458 -4.719710350036621
3.047196626663208 -5.069793701171875
3.0526835918426514 -4.943509101867676
3.0518627166748047 -4.983471870422363
3.0502660274505615 -4.943111419677734
3.0502707958221436 -4.943755149841309
3.04805588722229 -5.067213535308838
3.048225164413452 -5.119924545288086
3.050424337387085 -5.258907318115234
3.0534584522247314 -5.144019603729248
3.0517117977142334 -5.091532230377197
3.0527141094207764 -4.979922294616699
3.0549473762512207 -4.7463884353637695
3.054516077041626 -4.718114852905273
3.048694610595703 -4.291582107543945
3.042479991912842 -4.558900356292725
3.0423500537872314 -4.6163105964660645
3.0367088317871094 -4.8846755027771
3.0367166996002197 -4.908007621765137
3.0368154048919678 -4.851

In [7]:

print(input)
output=m(input)
print(output.size())

SyntaxError: invalid syntax (Temp/ipykernel_28412/1317620993.py, line 3)

In [9]:
m = nn.Linear(20,30)

input=(torch.randn(128,20)
       output=m(input)
print(output.size())
       
       
       

SyntaxError: invalid syntax (Temp/ipykernel_28412/314604165.py, line 4)